#~# Dockerfile to create a Debian 8 Base image
#
# 2015-11-11: Ian T Price <I.Price@qmul.ac.uk>: Created v1.0

#~# Based on debian:latest image from dockerhub.io
FROM debian:latest
MAINTAINER "Ian T Price" <I.Price@qmul.ac.uk>

ENV container docker
