QMUL:
  restart: unless-stopped
  image: registry:2
  container_name: Registry_QMUL
  ports:
    - 5000:5000
#  environment:
#    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#    REGISTRY_HTTP_TLS_KEY:         /certs/domain.key
#    REGISTRY_AUTH:                 htpasswd
#    REGISTRY_AUTH_HTPASSWD_PATH:   /auth/htpasswd
#    REGISTRY_AUTH_HTPASSWD_REALM:  Registry Realm
  volumes:
    - /var/lib:/var/lib/registry
#    - /path/certs:/certs
#    - /path/auth:/auth
