# 2015-11-18 Ian T Price <I.Price@qmul.ac.uk>

# Use busybox offical repo as it's tiny - 1.1Mb

FROM busybox:latest
MAINTAINER  Ian T Price <I.Price@qmul.ac.uk>

#RUN yum -y update; yum clean all

VOLUME /var/lib/mysql

VOLUME /var/www/html

# No CMD or ENTRYPOINT required for data containers - they don't need to be running

