#~# Dockerfile to create a Centos 6 Apache image to use with Compose

# File to produce image with Apache configured and to be used with Compose
# This will use the latest version of Apache - V2.4.x

# 2015-11-23 I.Price@qmul.ac.uk : Orignal file


#~# Based on Centos 6 qmul/base:v1.0
FROM qmul/centos6_base:v1.0
MAINTAINER Ian T Price <I.Price@qmul.ac.uk>

#~# Run yum update & install all base packages:
#~# - httpd mod_extract_forwarded mysql php php-cli
  php-common
  php-mysql
  php-pear

RUN yum install -y        \
  httpd                   \
  mod_extract_forwarded   \
  mysql                   \
  php                     \
  php-cli                 \
  php-common              \
  php-mysql               \
  php-pear                \
  ; yum clean all

## Setup the Apache httpd

# Add check files
ADD phpinfo.php /var/www/html/phpinfo.php
RUN echo "Apache HTTPD by Docker" >> /var/www/html/index.html

#RUN mkdir -p /etc/httpd/conf.d
ADD mod_extract_forwarded.conf /etc/httpd/conf.d/mod_extract_forwarded.conf

# Copy and run the Apache setup script
ADD centos6_apache_setup.sh /root/setup.sh
RUN chmod +x /root/setup.sh && /root/setup.sh && rm -f /root/setup.sh

# Simple startup script to avoid some issues observed with container restart 
ADD run-httpd.sh /run-httpd.sh
RUN chmod -v +x /run-httpd.sh

CMD ["/run-httpd.sh"]
# CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
