# QMUL centos6_lamp

# File to produce image with Apache configured
# This will be the latest version - V2.4.x

# 2015-11-18 Ian T Price <I.Price@qmul.ac.uk>


FROM qmul/centos6_base:v1.0

MAINTAINER Ian T Price <I.Price@qmul.ac.uk>


# Install Apache software components
RUN yum install -y        \
  httpd                   \
  mod_extract_forwarded   \
  mysql                   \
  php                     \
  php-cli                 \
  php-common              \
  php-mysql               \
  php-pear                \
  ; yum clean all

## Setup the Apache httpd

# Add check files
ADD phpinfo.php /var/www/html/phpinfo.php
RUN yum -y install httpd; yum clean all
RUN echo "Apache HTTPD by Docker" >> /var/www/html/index.html

#RUN mkdir -p /etc/httpd/conf.d
ADD mod_extract_forwarded.conf /etc/httpd/conf.d/mod_extract_forwarded.conf

# This may or may not cause issues - needs checking
#RUN sed -i 's/^UseCanonicalName Off$/UseCanonicalName On/' /etc/httpd/conf/httpd.conf

EXPOSE 80

# Simple startup script to avoid some issues observed with container restart 
ADD run-httpd.sh /run-httpd.sh
RUN chmod -v +x /run-httpd.sh

# CMD ["/run-httpd.sh"]
CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
