lnk_mysql:
  image: mysql
  hostname: lnk_mysql
  domainname: qmul.ac.uk
  volumes_from:
   - lnk_vol
  environment:
   - MYSQL_ROOT_PASSWORD=wpdocker
   - MYSQL_DATABASE=wordpress
   - MYSQL_USER=wordpress
   - MYSQL_PASSWORD=wordpresspwd

