# 2015-11-17 Ian T Price <I.Price@qmul.ac.uk>

FROM centos:centos6
MAINTAINER The CentOS Project <cloud-ops@centos.org>
MAINTAINER Ian T Price <I.Price@qmul.ac.uk>

RUN yum -y update; yum clean all
RUN yum -y install openssh-server passwd; yum clean all

# Setup sshd
# This creates the ssh directories & set-up files
RUN (service sshd start && service sshd stop)

# Allow root to ssh into the server
RUN sed -i 's/^#PermitRootLogin\syes$/PermitRootLogin yes/' /etc/ssh/sshd_config

# Prevent slow response from ssh by turning off DNS
RUN sed -i 's/^#UseDNS yes$/UseDNS no/' /etc/ssh/sshd_config

# Configure root ssh set-up
ADD id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 400 /root/.ssh/authorized_keys
RUN chown root:root /root/.ssh/authorized_keys

# Run the ssh server
# ENTRYPOINT ["/usr/sbin/sshd", "-D"]
